import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <img src="" alt="" className='logo' />
        <a href="/">Home</a>
        <a href="./about-us">About Us</a>
        <a href="./events/">Events</a>
      </header>
      <main className={styles.main}>
        <a href="./events/events-in-london">
          <h2>Events in London</h2>
          <p>Labore amet do exercitation aliqua id voluptate eiusmod duis qui. Veniam ut velit deserunt laboris ut. Excepteur incididunt id duis labore ad cupidatat ea proident ut eiusmod. Culpa eu Lorem qui ad excepteur aute amet dolor fugiat ipsum consectetur irure. Velit pariatur ex laboris excepteur commodo et. Enim esse ex officia elit culpa aliqua proident ipsum culpa id anim cillum.</p>
        </a>
        <a href='events/events-in-barcelona/'>
          <h2>Events in Barcelona</h2>
          <p>Labore amet do exercitation aliqua id voluptate eiusmod duis qui. Veniam ut velit deserunt laboris ut. Excepteur incididunt id duis labore ad cupidatat ea proident ut eiusmod. Culpa eu Lorem qui ad excepteur aute amet dolor fugiat ipsum consectetur irure. Velit pariatur ex laboris excepteur commodo et. Enim esse ex officia elit culpa aliqua proident ipsum culpa id anim cillum.</p>
        </a>
        <a href='events/events-in-san-fransisco/'>
          <h2>Events in San Fransisco</h2>
          <p>Labore amet do exercitation aliqua id voluptate eiusmod duis qui. Veniam ut velit deserunt laboris ut. Excepteur incididunt id duis labore ad cupidatat ea proident ut eiusmod. Culpa eu Lorem qui ad excepteur aute amet dolor fugiat ipsum consectetur irure. Velit pariatur ex laboris excepteur commodo et. Enim esse ex officia elit culpa aliqua proident ipsum culpa id anim cillum.</p>
        </a>


      </main>
      <footer>
        &copy; copyright Sheikh Abdullah Sharif - 2023
      </footer>
    </>
  )
}
