import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <img src="" alt="" className='logo' />
        <a href="/">Home</a>
        <a href="./about-us">About Us</a>
        <a href="./events/">Events</a>
      </header>
      <main className={styles.main}>
        {
          data.map(ev => (<a key={ev.id} href={`./events/${ev.id}`}>
            <Image src={ev.image} height={200} width={200} />
            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </a>))
        }


      </main>
      <footer>
        &copy; copyright Sheikh Abdullah Sharif - 2023
      </footer>
    </>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");

  return {
    props: {
      data: events_categories
    }
  }
}